site_name: Becki Lee's Portfolio
site_url: https://omgbeckilee.com
nav:
    - Writing samples: index.md
    - About me: about.md
    - Skills and tools: tools.md
theme:
  name: material
  palette:
    primary: green
    accent: blue
    scheme: slate
  font:
    code: Source Code Pro
    text: Lato
  icon:
    logo: material/book-heart
  favicon: images/favicon.svg
  features:
    - navigation.footer
    - navigation.expand
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:becki.lee@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/beckilee
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/becki-lee-10181562/
  analytics:
    provider: google
    property: G-5WSGN2D3GL
copyright: Copyright &copy; 2024 Becki Lee
markdown_extensions:
  - toc:
      permalink: ⚓︎
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - stylesheets/extra.css