site_name: Becki Lee's Portfolio
site_url: https://omgbeckilee.com
nav:
    - Home: index.md
    - Documentation samples:
      - File streaming: doc-file-streaming.md
      - Registering an application with Azure Active Directory: doc-akv-app-registration.md
      - Repeat while loop: doc-repeat-while-loop.md
      - Debugging a rule with Regula: doc-example-debugging-rule.md
      - Regula pre-commit hook: doc-regula-precommit-hook.md
      - Data retention API: doc-embedded-api-data-retention.md
      - Scan a Snyk Cloud Environment: doc-scan-snyk-cloud-environment.md
    - Blog samples:
      - Rego 101 series: blog-rego-101.md
      - Check Terraform using Regula and OPA: blog-check-terraform-with-regula.md
      - Securing a Kubernetes pod with Regula and OPA: blog-regula-kubernetes.md
      - Azure Virtual Network series: blog-azure-vnet-endpoints.md
      - AWS VPC endpoints: blog-aws-vpc-endpoints.md
    - Code samples:
      - Python: python.md
      - Rego: rego.md
    - About:
      - Experience: about.md
      - Technical skills: tools.md
    - Tags: tags.md
theme:
  name: material
  palette:
    primary: green
    accent: blue
    scheme: slate
  font:
    code: Source Code Pro
    text: Lato
  icon:
    logo: material/book-heart
    admonition:
      abstract: octicons/link-16
  favicon: images/favicon.svg
  features:
    - navigation.footer
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:becki.lee@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/beckilee
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/becki-lee-10181562/
  analytics:
    provider: google
    property: G-5WSGN2D3GL
markdown_extensions:
  - toc:
      permalink: ⚓︎
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - tags:
      tags_file: tags.md